import {
  ArrowLeftRight,
  BarChart3,
  Bell,
  Building2,
  Columns3,
  Factory,
  FlaskConical,
  FolderKanban,
  GitBranch,
  Globe2,
  History,
  Layers,
  Link2,
  ListChecks,
  MessageCircle,
  Network,
  PieChart,
  Table2,
  Target,
  TriangleAlert,
  Users,
  Wallet,
  Waypoints,
  Workflow,
  LayoutGrid,
  LineChart,
  ShieldCheck,
  TrendingUp,
  type LucideIcon,
} from "lucide-react";

/** Registre d'icônes utilisé par la nav (lib/nav-config.ts référence ces noms en string) et par les
 * sélecteurs de widgets des dashboards exécutif et RH (lib/dashboardWidgets.ts /
 * lib/hrDashboardWidgets.ts, champ `icon`). */
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  PieChart,
  Layers,
  Target,
  FlaskConical,
  BarChart3,
  TriangleAlert,
  ListChecks,
  MessageCircle,
  LineChart,
  History,
  Users,
  Factory,
  Building2,
  FolderKanban,
  Workflow,
  Network,
  ShieldCheck,
  Bell,
  Columns3,
  GitBranch,
  Link2,
  Table2,
  LayoutGrid,
  TrendingUp,
  ArrowLeftRight,
  Globe2,
  Wallet,
  Waypoints,
};
