import {
  BarChart3,
  Building2,
  Factory,
  FlaskConical,
  FolderKanban,
  History,
  Layers,
  ListChecks,
  MessageCircle,
  Network,
  PieChart,
  Target,
  TriangleAlert,
  Users,
  Workflow,
  LineChart,
  ShieldCheck,
  type LucideIcon,
} from "lucide-react";

/** Registre d'icônes utilisé par la nav (lib/nav-config.ts référence ces noms en string). */
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  PieChart,
  Layers,
  Target,
  FlaskConical,
  BarChart3,
  TriangleAlert,
  ListChecks,
  MessageCircle,
  LineChart,
  History,
  Users,
  Factory,
  Building2,
  FolderKanban,
  Workflow,
  Network,
  ShieldCheck,
};
